version: '3.8'  # Docker Compose version

services:
  # Define the MySQL database service
  mysql-db:
    image: mysql:8.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker    # Activates the docker profile
    ports:
      - "3307:3306"  # Map host port 3306 to container port 3306
    volumes:
     - ./mysql_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - spring-boot-network

  # Define the Spring Boot application service
  spring-boot-app:
    build:
      context: .  # Build context, where the Dockerfile is located
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Automatically update schema
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    depends_on:
      - mysql-db  # Ensure Spring Boot app starts after MySQL
    networks:
      - spring-boot-network

# Volumes for persisting data
volumes:
  mysql_data:

networks:
  spring-boot-network:
    driver: bridge
